# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Workshop on Computational Aspects of Pattern Recognition and Computer Vision with Neural Systems
email: michal.wozniak@pwr.edu.pl
description: > # Computational requirements on information processing systems are nowadays enormous - not only huge amounts of data needs to be processed and classified but also the systems need to deal with massive data usually in the form of data streams and frequently real-time processing requirements. On the other hand, neural systems proved their great potential, especially in pattern recognition and computer vision.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://caprikssk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
