# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Workshop on Machine Learning in Life Sciences
email: michal.wozniak@pwr.edu.pl
description: > # this means to ignore newlines until "baseurl:"
  Life sciences, ranging from medicine, biology and genetics to biochemistry and pharmacology have developed rapidly in previous years. Computerization of those domains allowed to gather and store enormous collections of data. Analysis of such vast amounts of information without any support is impossible for human being. Therefore recently machine learning and pattern recognition methods have attracted the attention of broad spectrum of experts from life sciences domain.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mlls.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
